[toolchain]
anchor_version = "0.31.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
helix_staking = "E9B7BsxdPS89M66CRGGbsCzQ9LkiGv6aNsra3cNBJha7"

[programs.devnet]
helix_staking = "E9B7BsxdPS89M66CRGGbsCzQ9LkiGv6aNsra3cNBJha7"

[programs.mainnet]
helix_staking = "<MAINNET_PROGRAM_ID>"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
